### ISSUE TITLE
Add gitignore

### ISSUE THREAD

**Issue by mgnisia** [simonaertssen/large_scale_gpus#1]
Hey simon :) 

you might be wondering why i came across your repo :) i am old school friend of louis who just stared the repo and i saw in my github feed. I would just recommend to you to add a `.gitignore` 👍 the default one for mac is this one:  https://github.com/github/gitignore/blob/master/Global/macOS.gitignore

Greetings from Munich
Moritz

**Comment by simonaertssen** [comment]
Hi Moritz,


Thanks for the tip. 


Simon Aertssen

**Comment by mgnisia** [comment]
You should also remove the .DS_Store `git rm .DS_Store` ;-) the `gitignore` reflects only future submissions, once a file is included it wont be excluded directly

**Comment by simonaertssen** [comment]
Thanks man!
